Milestone 3 - Interactivity
Mupa1/Bookstore pull request #3
Opened 2020-12-18 19:48 UTC by Mupa1

## Milestone 3 - Interactivity

In this milestone, I:-
- Added a delete button for each book on the BooksList component.
- Added logic for an interactive form on the BooksForm component.

Kindly review my project.

2020-12-18 20:35 UTC, bellom requested changes
## Hi @Mupa1  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 

# Status: Changes Required! ♻️ 

**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-12-18 20:35 UTC, bellom commented on src/containers/BooksForm.js
> +        category: '',
Awesome job trying to catch empty input.
But in React, it is not professional to use `document.getElementById`
Let's look into a better way of doing this;

Kindly take look at this 👉  https://dev.to/cesareferrari/how-to-display-error-messages-in-a-react-application-3g48

2020-12-19 10:55 UTC, Mupa1 commented
Thank you @bellom for your feedback and for sharing the resource. 

I have made the changes requested.

2020-12-19 11:28 UTC, bellom approved these changes
## Hi @Mupa1  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next milestone :slightly_smiling_face:_ 

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-12-19 11:39 UTC, merged